export ALTERNATE_EDITOR=""

case "$(uname)" in
  Darwin)
    source ~/.zprofile
    source ~/.zsh/mac.zsh
  ;;
  Linux)
    # commands for Linux go here
    source ~/.zprofile
    source ~/.zsh/linux.zsh
  ;;
  FreeBSD)
    # commands for FreeBSD go here
  ;;
esac

if [[ -d ~/linkedin-zsh ]]; then
  for file in ~/linkedin-zsh/*; do
    source $file
  done
fi

if (( $+commands[nvim] )) {
  export EDITOR="nvim"
  export VISUAL="nvim"
} elif (( $+commands[vim] )) {
  export EDITOR="vim"
  export VISUAL="vim"
} else {
  export EDITOR="vi"
  export VISUAL="vi"
}


if (( $+commands[alacritty] )) {
  export TERMINAL='alacritty'
} elif (( $+commands[urxvt256c] )) {
  export TERMINAL='urxvt256c'
} elif (( $+commands[urxvt] )) {
  export TERMINAL='urxvt'
} else {
  export TERMINAL='xterm'
}

#alias emax="emacsclient -t"
#alias semac="sudo emacsclient -t"
#alias emacsc="emacsclient -c -a emacs"

# lets go into vim mode...yay??
bindkey -v
export KEYTIMEOUT=25

# OPAM configuration
. /home/dino/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true

# General setopts
source ~/.zsh/opts.zsh
# Pretty prompt
source ~/.zsh/prompt.zsh
# General Aliases
source ~/.zsh/aliases.zsh
# Save history
source ~/.zsh/history.zsh
# Numbers to traverse directory stack
for index ({1..9}) alias "$index"="cd +${index}"; unset index
# More completions
fpath=(/export/content/linkedin/etc/zsh ~/.zsh/zsh-completions/src ~/.zsh/completion $fpath)
# Add some completion configuration
source ~/.zsh/completion.zsh
# Pretty syntax highlighting
source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export GPG_TTY="$(tty)"

export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
