export ALTERNATE_EDITOR=""

if (( $+commands[nvim] )) {
	export EDITOR="nvim"
	export VISUAL="nvim"
} elif (( $+commands[vim] )) {
	export EDITOR="vim"
	export VISUAL="vim"
} else {
	export EDITOR="vi"
	export VISUAL="vi"
}

#alias emax="emacsclient -t"
#alias semac="sudo emacsclient -t"
#alias emacsc="emacsclient -c -a emacs"

# lets go into vim mode...yay??
bindkey -v
export KEYTIMEOUT=1

# General setopts
source ~/.zsh/opts.zsh
# Pretty prompt
source ~/.zsh/prompt.zsh
# General Aliases
source ~/.zsh/aliases.zsh
# Save history
source ~/.zsh/history.zsh
# Numbers to traverse directory stack
for index ({1..9}) alias "$index"="cd +${index}"; unset index
# More completions
fpath=(~/.zsh/zsh-completions/src $fpath)
# Add some completion configuration
source ~/.zsh/completion.zsh
# Pretty syntax highlighting
source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
